# Generated by Django 5.0 on 2024-01-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
